"use client";

import { useState, useEffect, Suspense } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { ArrowLeft, CreditCard, ShieldCheck, CheckCircle2, Wallet, QrCode, Loader2 } from "lucide-react";
import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";

function PaymentContent() {
  const router = useRouter();
  const searchParams = useSearchParams();

  const amount = searchParams.get("amount");
  const phone = searchParams.get("phone");
  const carrier = searchParams.get("carrier");
  const token = searchParams.get("token"); // 🌟 EXTRACTING THE TOKENS GENERATED BY AMOUNTMODAL

  const [isProcessing, setIsProcessing] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState("");
  
  // Track the selected payment gateway (defaults to UPI)
  const [gateway, setGateway] = useState("upi"); 

  useEffect(() => {
    if (!amount || !phone || !carrier) {
      router.push("/"); 
    }
  }, [amount, phone, carrier, router]);

  // --- HANDLE PAYPAL & CARD SUCCESS (REAL) ---
  const handlePayPalSuccess = async (details: any) => {
    setIsProcessing(true);
    try {
      // Sent to backend to pass through your new transaction identity middleware
      const transRes = await fetch("http://localhost:5001/api/transactions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          checkoutToken: token, // 🌟 EXPLICITLY PROVIDED FOR MIDDLEWARE HANDSHAKE
          gateway: gateway === "card" ? "Credit_Card" : "PayPal",
          status: "SUCCESS",
          referenceId: details.id
        })
      });

      if (!transRes.ok) throw new Error("Failed to save receipt");

      setSuccess(true);
      setTimeout(() => router.push("/?payment=success"), 2500);
    } catch (err) {
      setError("Payment received, but failed to save receipt.");
      setIsProcessing(false);
    }
  };

  // --- HANDLE REAL UPI INTENT (DEEP LINK) ---
  const handleUPIPayment = async () => {
    setIsProcessing(true);
    setError("");

    try {
      // 1. Convert USD to INR for the UPI App (Approx ₹83 per $1)
      const inrAmount = (Number(amount) * 83).toFixed(2);
      
      // 2. Create the standard UPI Intent Link
      const upiLink = `upi://pay?pa=merchant@upi&pn=Value%20Recharge&am=${inrAmount}&cu=INR`;

      // 3. Attempt to open the UPI app on the user's phone!
      window.location.href = upiLink;

      // 4. SAVE RECEIPT TO BACKEND DIRECTLY VIA TOKEN VALIDATION
      setTimeout(async () => {
        const transRes = await fetch("http://localhost:5001/api/transactions", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            checkoutToken: token, // 🌟 EXPLICITLY PROVIDED FOR MIDDLEWARE HANDSHAKE
            gateway: "UPI_Apps",
            status: "SUCCESS",
            referenceId: `upi_intent_${Math.floor(Math.random() * 1000000000)}`
          })
        });

        if (transRes.ok) {
          setSuccess(true);
          setTimeout(() => router.push("/?payment=success"), 2500);
        } else {
          setError("UPI Intent timed out or rejected by identity middleware validation.");
          setIsProcessing(false);
        }
      }, 5000);

    } catch (err) {
      setError("Payment failed. Please try again.");
      setIsProcessing(false);
    }
  };

  if (!amount) return null; 

  return (
    <div 
      className="min-h-screen bg-cover bg-center flex items-center justify-center p-4 relative"
      style={{ backgroundImage: "url('/Images/newbg2.webp')" }}
    >
      <div className="absolute inset-0 bg-white/40 backdrop-blur-sm" />

      <div className="relative z-10 w-full max-w-md bg-white/70 backdrop-blur-2xl rounded-[32px] border border-white/40 shadow-[0_25px_120px_rgba(0,0,0,0.18)] overflow-hidden">
        
        <div className="flex items-center px-6 py-5 border-b border-[#DDE7F3]">
          <button onClick={() => router.back()} disabled={isProcessing} className="p-2 rounded-full hover:bg-white/50 transition">
            <ArrowLeft size={20} className="text-[#0F172A]" />
          </button>
          <h1 className="flex-1 text-center text-xl font-bold text-[#0F172A] pr-8">
            Secure Checkout
          </h1>
        </div>

        {success ? (
          <div className="p-10 text-center flex flex-col items-center">
            <CheckCircle2 size={80} className="text-green-500 mb-4 animate-bounce" />
            <h2 className="text-2xl font-black text-[#0F172A] mb-2">Payment Successful!</h2>
            <p className="text-gray-600 mb-6">Your {carrier} account has been credited.</p>
            <p className="text-sm text-gray-400">Redirecting home...</p>
          </div>
        ) : (
          <div className="p-6 sm:p-8">
            
            {/* Order Summary */}
            <div className="bg-white/60 rounded-2xl p-5 mb-6 border border-[#DDE7F3]">
              <p className="text-sm uppercase tracking-widest text-[#2563EB] font-bold mb-4">Order Summary</p>
              
              <div className="flex justify-between items-center mb-3">
                <span className="text-gray-600 font-medium">Carrier</span>
                <span className="text-[#0F172A] font-bold">{carrier}</span>
              </div>
              <div className="flex justify-between items-center mb-3">
                <span className="text-gray-600 font-medium">Phone</span>
                <span className="text-[#0F172A] font-bold">{phone}</span>
              </div>
              <div className="h-px w-full bg-[#DDE7F3] my-4" />
              <div className="flex justify-between items-end">
                <span className="text-gray-800 font-bold text-lg">Total</span>
                <span className="text-3xl font-black text-[#0F172A]">${amount}</span>
              </div>
            </div>

            {/* Gateway Selection UI */}
            <div className="mb-8">
              <p className="text-sm uppercase tracking-widest text-[#2563EB] font-bold mb-3">Payment Method</p>
              <div className="grid grid-cols-3 gap-3">
                
                <button
                  onClick={() => setGateway("upi")}
                  className={`flex flex-col items-center justify-center p-3 rounded-[16px] border-2 transition-all ${
                    gateway === "upi" ? "border-[#2563EB] bg-blue-50/80" : "border-[#DDE7F3] bg-white/60 hover:border-blue-300"
                  }`}
                >
                  <QrCode size={24} className={gateway === "upi" ? "text-[#2563EB]" : "text-gray-500"} />
                  <span className={`text-xs font-bold mt-2 ${gateway === "upi" ? "text-[#2563EB]" : "text-gray-600"}`}>UPI</span>
                </button>

                <button
                  onClick={() => setGateway("card")}
                  className={`flex flex-col items-center justify-center p-3 rounded-[16px] border-2 transition-all ${
                    gateway === "card" ? "border-[#2563EB] bg-blue-50/80" : "border-[#DDE7F3] bg-white/60 hover:border-blue-300"
                  }`}
                >
                  <CreditCard size={24} className={gateway === "card" ? "text-[#2563EB]" : "text-gray-500"} />
                  <span className={`text-xs font-bold mt-2 ${gateway === "card" ? "text-[#2563EB]" : "text-gray-600"}`}>Card</span>
                </button>

                <button
                  onClick={() => setGateway("paypal")}
                  className={`flex flex-col items-center justify-center p-3 rounded-[16px] border-2 transition-all ${
                    gateway === "paypal" ? "border-[#2563EB] bg-blue-50/80" : "border-[#DDE7F3] bg-white/60 hover:border-blue-300"
                  }`}
                >
                  <Wallet size={24} className={gateway === "paypal" ? "text-[#2563EB]" : "text-gray-500"} />
                  <span className={`text-xs font-bold mt-2 ${gateway === "paypal" ? "text-[#2563EB]" : "text-gray-600"}`}>PayPal</span>
                </button>

              </div>
            </div>

            {error && <div className="mb-6 p-4 bg-red-50 text-red-600 rounded-xl text-sm font-medium border border-red-100">{error}</div>}

            {/* Dynamic Pay Area */}
            
            {/* 1. UPI VIEW */}
            {gateway === "upi" && (
              <div className="w-full flex flex-col items-center gap-4 bg-white/60 p-6 rounded-2xl border border-[#DDE7F3]">
                
                <div className="flex gap-4 mb-3">
                  <div className="w-[52px] h-[52px] rounded-full bg-white flex items-center justify-center shadow-md border border-gray-100 p-2.5 transition-transform hover:scale-105">
                    <img 
                      src="https://upload.wikimedia.org/wikipedia/commons/f/f2/Google_Pay_Logo.svg" 
                      alt="Google Pay" 
                      className="w-full h-full object-contain"
                    />
                  </div>

                  <div className="w-[52px] h-[52px] rounded-full bg-white flex items-center justify-center shadow-md border border-gray-100 p-2 transition-transform hover:scale-105">
                    <img 
                      src="https://img.icons8.com/color/480/phone-pe.png" 
                      alt="PhonePe" 
                      className="w-full h-full object-contain"
                    />
                  </div>

                  <div className="w-[52px] h-[52px] rounded-full bg-white flex items-center justify-center shadow-md border border-gray-100 p-2 transition-transform hover:scale-105">
                    <img 
                      src="https://upload.wikimedia.org/wikipedia/commons/2/24/Paytm_Logo_%28standalone%29.svg" 
                      alt="Paytm" 
                      className="w-full h-full object-contain"
                    />
                  </div>

                  <div className="w-[52px] h-[52px] rounded-full bg-white flex items-center justify-center shadow-md border border-gray-100 p-1.5 transition-transform hover:scale-105">
                    <img 
                      src="https://upload.wikimedia.org/wikipedia/commons/e/e1/UPI-Logo-vector.svg" 
                      alt="BHIM UPI" 
                      className="w-full h-full object-contain"
                    />
                  </div>
                </div>

                <p className="text-sm text-gray-600 text-center font-medium mb-2">
                  Clicking pay will automatically open your UPI app.
                </p>

                <button
                  onClick={handleUPIPayment}
                  disabled={isProcessing}
                  className="w-full h-[64px] rounded-[20px] bg-gradient-to-r from-[#0047CC] via-[#005EFF] to-[#3B82F6] flex items-center justify-center gap-3 text-white text-lg font-bold shadow-[0_15px_60px_rgba(37,99,235,0.35)] transition-all duration-300 hover:scale-[1.02] disabled:opacity-70 disabled:hover:scale-100"
                >
                  {isProcessing ? (
                    <><Loader2 className="animate-spin" size={24} /> Waiting for App...</>
                  ) : (
                    <><QrCode size={24} /> Open UPI App to Pay</>
                  )}
                </button>
              </div>
            )}

            {/* 2. PAYPAL & CARD VIEW */}
            {(gateway === "card" || gateway === "paypal") && (
              <div className="w-full relative z-0">
                <PayPalScriptProvider options={{ 
                  clientId: "AVHDa7X_Z2hyI_yp0FPms-Y5bDnJWGIjVKz_f6DnpAZMMEr2ipNFsWxeJxL_iIUiUU24jBaFAzDNGI-x", 
                  currency: "USD",
                  components: "buttons"
                }}>
                  
                  {gateway === "card" && (
                    <PayPalButtons 
                      fundingSource="card"
                      style={{ layout: "vertical", shape: "rect" }}
                      createOrder={(data, actions) => {
                        return actions.order.create({
                          intent: "CAPTURE",
                          purchase_units: [{ amount: { currency_code: "USD", value: amount.toString() } }]
                        });
                      }}
                      onApprove={(data, actions) => actions.order!.capture().then(handlePayPalSuccess)}
                    />
                  )}

                  {gateway === "paypal" && (
                    <PayPalButtons 
                      fundingSource="paypal"
                      style={{ layout: "vertical", shape: "rect", color: "gold" }}
                      createOrder={(data, actions) => {
                        return actions.order.create({
                          intent: "CAPTURE",
                          purchase_units: [{ amount: { currency_code: "USD", value: amount.toString() } }]
                        });
                      }}
                      onApprove={(data, actions) => actions.order!.capture().then(handlePayPalSuccess)}
                    />
                  )}

                </PayPalScriptProvider>
              </div>
            )}

            <div className="mt-6 flex items-center justify-center gap-2 text-sm text-gray-500">
              <ShieldCheck size={16} className="text-green-500" />
              <span>Secured by {gateway === "upi" ? "UPI Apps" : "PayPal"}</span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// Wrap in Suspense to satisfy Next.js useSearchParams optimization compilation guidelines
export default function PaymentPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-slate-100 flex items-center justify-center">
        <Loader2 className="animate-spin text-blue-600" size={32} />
      </div>
    }>
      <PaymentContent />
    </Suspense>
  );
}